version: '3.7'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 8001:5000
    volumes:
      - ./backend/:/home/
    command: tail -f /dev/null
  
  frontend:
    image: node:current-bullseye

    ports:
      - 80:3000
    volumes:
      - ./frontend/:/home/
    working_dir: /home
    depends_on:
      - backend
    command: bash -c "npm install && node app.js && tail -f /dev/null"
